#!/usr/bin/env bash
set -euo pipefail

exec chromium \
  --ozone-platform=wayland \
  --enable-features=UseOzonePlatform,VaapiVideoDecoder \
  --enable-gpu-rasterization \
  --disable-software-rasterizer \
  "$@"

